
/*
 * PickPhotosSearchQuery.java
 *
 * Created on Mar 7, 2011, 4:39:42 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class Export extends BaseUi {

    /** Creates new form PickPhotosSearchQuery */
    public Export() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                exportTitle = new javax.swing.JLabel();
                resultsButton = new javax.swing.JButton();
                resultsButton1 = new javax.swing.JButton();
                resultsButton2 = new javax.swing.JButton();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(Export.class);
                exportTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                exportTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                exportTitle.setText(resourceMap.getString("exportTitle.text")); // NOI18N
                exportTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                exportTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                exportTitle.setName("exportTitle"); // NOI18N
                exportTitle.setOpaque(true);

                resultsButton.setText(resourceMap.getString("resultsButton.text")); // NOI18N
                resultsButton.setName("resultsButton"); // NOI18N

                resultsButton1.setText(resourceMap.getString("resultsButton1.text")); // NOI18N
                resultsButton1.setName("resultsButton1"); // NOI18N

                resultsButton2.setText(resourceMap.getString("resultsButton2.text")); // NOI18N
                resultsButton2.setName("resultsButton2"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(resultsButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(resultsButton2))
                                        .addComponent(resultsButton1))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(exportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(resultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resultsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(239, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel exportTitle;
        private javax.swing.JButton resultsButton;
        private javax.swing.JButton resultsButton1;
        private javax.swing.JButton resultsButton2;
        // End of variables declaration//GEN-END:variables

}
