
/*
 * ImagesDashboard.java
 *
 * Created on Mar 7, 2011, 4:05:47 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class ImagesDashboard extends javax.swing.JPanel {

    /** Creates new form ImagesDashboard */
    public ImagesDashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                downloadButton = new javax.swing.JButton();
                keywordsLabel = new javax.swing.JLabel();
                chooseFolderButton = new javax.swing.JButton();
                keywordsList = new javax.swing.JList();
                foldersList = new javax.swing.JList();
                foldersLabel = new javax.swing.JLabel();
                orLabel = new javax.swing.JLabel();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(ImagesDashboard.class);
                downloadButton.setText(resourceMap.getString("downloadButton.text")); // NOI18N
                downloadButton.setName("downloadButton"); // NOI18N

                keywordsLabel.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                keywordsLabel.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                keywordsLabel.setText(resourceMap.getString("keywordsLabel.text")); // NOI18N
                keywordsLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                keywordsLabel.setName("keywordsLabel"); // NOI18N
                keywordsLabel.setOpaque(true);

                chooseFolderButton.setText(resourceMap.getString("chooseFolderButton.text")); // NOI18N
                chooseFolderButton.setName("chooseFolderButton"); // NOI18N
                chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chooseFolderButtonActionPerformed(evt);
                        }
                });

                keywordsList.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                keywordsList.setName("keywordsList"); // NOI18N

                foldersList.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                foldersList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                foldersList.setName("foldersList"); // NOI18N

                foldersLabel.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                foldersLabel.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                foldersLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                foldersLabel.setText(resourceMap.getString("foldersLabel.text")); // NOI18N
                foldersLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                foldersLabel.setName("foldersLabel"); // NOI18N
                foldersLabel.setOpaque(true);

                orLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                orLabel.setText(resourceMap.getString("orLabel.text")); // NOI18N
                orLabel.setName("orLabel"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(keywordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                                        .addComponent(downloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(orLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(keywordsList, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                                .addGap(65, 65, 65)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(foldersList, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                        .addComponent(foldersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(orLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(keywordsLabel)
                                        .addComponent(foldersLabel))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(keywordsList, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(foldersList, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chooseFolderButtonActionPerformed
    {//GEN-HEADEREND:event_chooseFolderButtonActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_chooseFolderButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton chooseFolderButton;
        private javax.swing.JButton downloadButton;
        private javax.swing.JLabel foldersLabel;
        private javax.swing.JList foldersList;
        private javax.swing.JLabel keywordsLabel;
        private javax.swing.JList keywordsList;
        private javax.swing.JLabel orLabel;
        // End of variables declaration//GEN-END:variables

}
