
/*
 * ImagesSearchResults.java
 *
 * Created on Mar 7, 2011, 4:40:03 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class ImagesSearchResults extends javax.swing.JPanel {

    /** Creates new form ImagesSearchResults */
    public ImagesSearchResults() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                searchResultsTitle = new javax.swing.JLabel();
                editQueryButton = new javax.swing.JButton();
                pagingCombobox = new javax.swing.JComboBox();
                helpLabel = new javax.swing.JLabel();
                horizontalSeparator = new javax.swing.JSeparator();
                progressButton = new javax.swing.JButton();
                downloadButton = new javax.swing.JButton();
                searchResultsScrollPane = new javax.swing.JScrollPane();

                setName("Form"); // NOI18N
                setPreferredSize(new java.awt.Dimension(810, 441));

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(ImagesSearchResults.class);
                searchResultsTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                searchResultsTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                searchResultsTitle.setText(resourceMap.getString("searchResultsTitle.text")); // NOI18N
                searchResultsTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                searchResultsTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                searchResultsTitle.setName("searchResultsTitle"); // NOI18N
                searchResultsTitle.setOpaque(true);

                editQueryButton.setText(resourceMap.getString("editQueryButton.text")); // NOI18N
                editQueryButton.setName("editQueryButton"); // NOI18N

                pagingCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18 per page", "36 per page", "72 per page" }));
                pagingCombobox.setName("pagingCombobox"); // NOI18N

                helpLabel.setText(resourceMap.getString("helpLabel.text")); // NOI18N
                helpLabel.setName("helpLabel"); // NOI18N

                horizontalSeparator.setName("horizontalSeparator"); // NOI18N

                progressButton.setText(resourceMap.getString("progressButton.text")); // NOI18N
                progressButton.setName("progressButton"); // NOI18N

                downloadButton.setText(resourceMap.getString("downloadButton.text")); // NOI18N
                downloadButton.setName("downloadButton"); // NOI18N

                searchResultsScrollPane.setName("searchResultsScrollPane"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                                        .addComponent(horizontalSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(searchResultsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editQueryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(187, 187, 187)
                                                .addComponent(pagingCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(helpLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(progressButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                                                .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchResultsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editQueryButton)
                                        .addComponent(pagingCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horizontalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(progressButton))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton downloadButton;
        private javax.swing.JButton editQueryButton;
        private javax.swing.JLabel helpLabel;
        private javax.swing.JSeparator horizontalSeparator;
        private javax.swing.JComboBox pagingCombobox;
        private javax.swing.JButton progressButton;
        private javax.swing.JScrollPane searchResultsScrollPane;
        private javax.swing.JLabel searchResultsTitle;
        // End of variables declaration//GEN-END:variables

}
