
/*
 * SfmSetup.java
 *
 * Created on Mar 9, 2011, 1:17:54 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class MvsSetup extends javax.swing.JPanel {

    /** Creates new form SfmSetup */
    public MvsSetup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                titleLabel = new javax.swing.JLabel();
                runCmvsButton = new javax.swing.JButton();
                runCmvsPmvsButton = new javax.swing.JButton();
                separatorBottom = new javax.swing.JSeparator();
                bundlerOutputTextField = new javax.swing.JTextField();
                bundlerOutputChangeButton = new javax.swing.JButton();
                bundlerOutputLabel = new javax.swing.JLabel();
                cmvsOptionsPanel = new javax.swing.JPanel();
                cmvsOptionsTitle = new javax.swing.JLabel();
                maximumImagesSpinner = new javax.swing.JSpinner();
                maximumImagesLabel = new javax.swing.JLabel();
                cpuLabel = new javax.swing.JLabel();
                cpuSpinner = new javax.swing.JSpinner();
                pmvsOptionsPanel = new javax.swing.JPanel();
                pmvsOptionsTitle = new javax.swing.JLabel();
                levelSpinner = new javax.swing.JSpinner();
                levelLabel = new javax.swing.JLabel();
                csizeLabel = new javax.swing.JLabel();
                csizeSpinner = new javax.swing.JSpinner();
                wsizeSpinner = new javax.swing.JSpinner();
                thresholdSpinner = new javax.swing.JSpinner();
                thresholdLabel = new javax.swing.JLabel();
                wsizeLabel = new javax.swing.JLabel();
                minimumImageSpinner = new javax.swing.JSpinner();
                minimumImageLabel = new javax.swing.JLabel();
                cpuPmvsLabel = new javax.swing.JLabel();
                cpuPmvsSpinner = new javax.swing.JSpinner();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(MvsSetup.class);
                titleLabel.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                titleLabel.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
                titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                titleLabel.setName("titleLabel"); // NOI18N
                titleLabel.setOpaque(true);

                runCmvsButton.setText(resourceMap.getString("runCmvsButton.text")); // NOI18N
                runCmvsButton.setName("runCmvsButton"); // NOI18N

                runCmvsPmvsButton.setText(resourceMap.getString("runCmvsPmvsButton.text")); // NOI18N
                runCmvsPmvsButton.setName("runCmvsPmvsButton"); // NOI18N

                separatorBottom.setName("separatorBottom"); // NOI18N

                bundlerOutputTextField.setText(resourceMap.getString("bundlerOutputTextField.text")); // NOI18N
                bundlerOutputTextField.setName("bundlerOutputTextField"); // NOI18N

                bundlerOutputChangeButton.setText(resourceMap.getString("bundlerOutputChangeButton.text")); // NOI18N
                bundlerOutputChangeButton.setName("bundlerOutputChangeButton"); // NOI18N

                bundlerOutputLabel.setText(resourceMap.getString("bundlerOutputLabel.text")); // NOI18N
                bundlerOutputLabel.setName("bundlerOutputLabel"); // NOI18N

                cmvsOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                cmvsOptionsPanel.setName("cmvsOptionsPanel"); // NOI18N

                cmvsOptionsTitle.setText(resourceMap.getString("cmvsOptionsTitle.text")); // NOI18N
                cmvsOptionsTitle.setName("cmvsOptionsTitle"); // NOI18N

                maximumImagesSpinner.setName("maximumImagesSpinner"); // NOI18N

                maximumImagesLabel.setText(resourceMap.getString("maximumImagesLabel.text")); // NOI18N
                maximumImagesLabel.setName("maximumImagesLabel"); // NOI18N

                cpuLabel.setText(resourceMap.getString("cpuLabel.text")); // NOI18N
                cpuLabel.setName("cpuLabel"); // NOI18N

                cpuSpinner.setName("cpuSpinner"); // NOI18N

                javax.swing.GroupLayout cmvsOptionsPanelLayout = new javax.swing.GroupLayout(cmvsOptionsPanel);
                cmvsOptionsPanel.setLayout(cmvsOptionsPanelLayout);
                cmvsOptionsPanelLayout.setHorizontalGroup(
                        cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cmvsOptionsPanelLayout.createSequentialGroup()
                                .addGroup(cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmvsOptionsTitle)
                                        .addGroup(cmvsOptionsPanelLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(cmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addComponent(cpuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cpuSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(cmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addComponent(maximumImagesLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(maximumImagesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(450, Short.MAX_VALUE))
                );
                cmvsOptionsPanelLayout.setVerticalGroup(
                        cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cmvsOptionsPanelLayout.createSequentialGroup()
                                .addComponent(cmvsOptionsTitle)
                                .addGap(6, 6, 6)
                                .addGroup(cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maximumImagesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .addComponent(maximumImagesSpinner))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cpuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .addComponent(cpuSpinner))
                                .addGap(20, 20, 20))
                );

                pmvsOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                pmvsOptionsPanel.setName("pmvsOptionsPanel"); // NOI18N

                pmvsOptionsTitle.setText(resourceMap.getString("pmvsOptionsTitle.text")); // NOI18N
                pmvsOptionsTitle.setName("pmvsOptionsTitle"); // NOI18N

                levelSpinner.setName("levelSpinner"); // NOI18N

                levelLabel.setText(resourceMap.getString("levelLabel.text")); // NOI18N
                levelLabel.setName("levelLabel"); // NOI18N

                csizeLabel.setText(resourceMap.getString("csizeLabel.text")); // NOI18N
                csizeLabel.setName("csizeLabel"); // NOI18N

                csizeSpinner.setName("csizeSpinner"); // NOI18N

                wsizeSpinner.setName("wsizeSpinner"); // NOI18N

                thresholdSpinner.setName("thresholdSpinner"); // NOI18N

                thresholdLabel.setText(resourceMap.getString("thresholdLabel.text")); // NOI18N
                thresholdLabel.setName("thresholdLabel"); // NOI18N

                wsizeLabel.setText(resourceMap.getString("wsizeLabel.text")); // NOI18N
                wsizeLabel.setName("wsizeLabel"); // NOI18N

                minimumImageSpinner.setName("minimumImageSpinner"); // NOI18N

                minimumImageLabel.setText(resourceMap.getString("minimumImageLabel.text")); // NOI18N
                minimumImageLabel.setName("minimumImageLabel"); // NOI18N

                cpuPmvsLabel.setText(resourceMap.getString("cpuPmvsLabel.text")); // NOI18N
                cpuPmvsLabel.setName("cpuPmvsLabel"); // NOI18N

                cpuPmvsSpinner.setName("cpuPmvsSpinner"); // NOI18N

                javax.swing.GroupLayout pmvsOptionsPanelLayout = new javax.swing.GroupLayout(pmvsOptionsPanel);
                pmvsOptionsPanel.setLayout(pmvsOptionsPanelLayout);
                pmvsOptionsPanelLayout.setHorizontalGroup(
                        pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pmvsOptionsTitle)
                                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(csizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(csizeSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(levelSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(wsizeLabel)
                                                        .addComponent(thresholdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(wsizeSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(thresholdSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(88, 88, 88)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cpuPmvsLabel)
                                                        .addComponent(minimumImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cpuPmvsSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(minimumImageSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                );
                pmvsOptionsPanelLayout.setVerticalGroup(
                        pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addComponent(minimumImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cpuPmvsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(minimumImageSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cpuPmvsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                .addComponent(pmvsOptionsTitle)
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(csizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(levelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(csizeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))))
                                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pmvsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addComponent(thresholdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wsizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                                                        .addGroup(pmvsOptionsPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(thresholdSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wsizeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(runCmvsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runCmvsPmvsButton))
                                        .addComponent(pmvsOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmvsOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bundlerOutputLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(bundlerOutputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bundlerOutputChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(separatorBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bundlerOutputLabel)
                                        .addComponent(bundlerOutputChangeButton)
                                        .addComponent(bundlerOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmvsOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pmvsOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(separatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(runCmvsPmvsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(runCmvsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bundlerOutputChangeButton;
        private javax.swing.JLabel bundlerOutputLabel;
        private javax.swing.JTextField bundlerOutputTextField;
        private javax.swing.JPanel cmvsOptionsPanel;
        private javax.swing.JLabel cmvsOptionsTitle;
        private javax.swing.JLabel cpuLabel;
        private javax.swing.JLabel cpuPmvsLabel;
        private javax.swing.JSpinner cpuPmvsSpinner;
        private javax.swing.JSpinner cpuSpinner;
        private javax.swing.JLabel csizeLabel;
        private javax.swing.JSpinner csizeSpinner;
        private javax.swing.JLabel levelLabel;
        private javax.swing.JSpinner levelSpinner;
        private javax.swing.JLabel maximumImagesLabel;
        private javax.swing.JSpinner maximumImagesSpinner;
        private javax.swing.JLabel minimumImageLabel;
        private javax.swing.JSpinner minimumImageSpinner;
        private javax.swing.JPanel pmvsOptionsPanel;
        private javax.swing.JLabel pmvsOptionsTitle;
        private javax.swing.JButton runCmvsButton;
        private javax.swing.JButton runCmvsPmvsButton;
        private javax.swing.JSeparator separatorBottom;
        private javax.swing.JLabel thresholdLabel;
        private javax.swing.JSpinner thresholdSpinner;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JLabel wsizeLabel;
        private javax.swing.JSpinner wsizeSpinner;
        // End of variables declaration//GEN-END:variables

}
