
/*
 * PickPhotosSearchQuery.java
 *
 * Created on Mar 7, 2011, 4:39:42 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class PickPhotosSearchQuery extends javax.swing.JPanel {

    /** Creates new form PickPhotosSearchQuery */
    public PickPhotosSearchQuery() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                verticalSeparator = new javax.swing.JSeparator();
                downloadOptionsTitle = new javax.swing.JLabel();
                siftPanel = new javax.swing.JPanel();
                siftCheckbox = new javax.swing.JCheckBox();
                siftLegend = new javax.swing.JTextArea();
                dimensionsPanel = new javax.swing.JPanel();
                dimensionsTitle = new javax.swing.JLabel();
                keepOriginalCheckbox = new javax.swing.JCheckBox();
                dim1024Checkbox = new javax.swing.JCheckBox();
                dim800Checkbox = new javax.swing.JCheckBox();
                newDimensionButton = new javax.swing.JButton();
                horizontalSeparator = new javax.swing.JSeparator();
                searchButton = new javax.swing.JButton();
                downloadProgressButton = new javax.swing.JButton();
                keywordsLabel = new javax.swing.JLabel();
                keywordsTextfield = new javax.swing.JTextField();
                uploadedDateSeparator = new javax.swing.JLabel();
                uploadedDateTillSpinner = new javax.swing.JSpinner();
                uploadedDateFromSpinner = new javax.swing.JSpinner();
                uploadedDateLabel = new javax.swing.JLabel();
                searchPhotosTitle = new javax.swing.JLabel();
                searchEngineCombobox = new javax.swing.JComboBox();
                gpsLatTextfield = new javax.swing.JTextField();
                gpsLonTextfield = new javax.swing.JTextField();
                gpsLabel = new javax.swing.JLabel();
                gpsRadiusTextfield = new javax.swing.JTextField();
                contextLabel = new javax.swing.JLabel();
                contextCombobox = new javax.swing.JComboBox();
                licenseLabel = new javax.swing.JLabel();
                licenseCombobox = new javax.swing.JComboBox();
                takenDateFromSpinner = new javax.swing.JSpinner();
                takenDateTillSpinner = new javax.swing.JSpinner();
                takenDateLabel = new javax.swing.JLabel();
                takenDateSeparator = new javax.swing.JLabel();
                downloadFolderButton = new javax.swing.JButton();
                downloadFolderTextfield = new javax.swing.JTextField();
                downloadFolderLabel = new javax.swing.JLabel();

                setName("Form"); // NOI18N
                setPreferredSize(new java.awt.Dimension(810, 441));

                verticalSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
                verticalSeparator.setName("verticalSeparator"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(PickPhotosSearchQuery.class);
                downloadOptionsTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                downloadOptionsTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                downloadOptionsTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                downloadOptionsTitle.setText(resourceMap.getString("downloadOptionsTitle.text")); // NOI18N
                downloadOptionsTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                downloadOptionsTitle.setName("downloadOptionsTitle"); // NOI18N
                downloadOptionsTitle.setOpaque(true);

                siftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                siftPanel.setName("siftPanel"); // NOI18N

                siftCheckbox.setText(resourceMap.getString("siftCheckbox.text")); // NOI18N
                siftCheckbox.setMargin(new java.awt.Insets(1, 0, 0, 1));
                siftCheckbox.setName("siftCheckbox"); // NOI18N

                siftLegend.setColumns(20);
                siftLegend.setFont(resourceMap.getFont("siftLegend.font")); // NOI18N
                siftLegend.setLineWrap(true);
                siftLegend.setRows(3);
                siftLegend.setText(resourceMap.getString("siftLegend.text")); // NOI18N
                siftLegend.setBorder(null);
                siftLegend.setName("siftLegend"); // NOI18N
                siftLegend.setOpaque(false);

                javax.swing.GroupLayout siftPanelLayout = new javax.swing.GroupLayout(siftPanel);
                siftPanel.setLayout(siftPanelLayout);
                siftPanelLayout.setHorizontalGroup(
                        siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(siftPanelLayout.createSequentialGroup()
                                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(siftCheckbox)
                                        .addGroup(siftPanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(siftLegend, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(34, Short.MAX_VALUE))
                );
                siftPanelLayout.setVerticalGroup(
                        siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(siftPanelLayout.createSequentialGroup()
                                .addComponent(siftCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siftLegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                dimensionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                dimensionsPanel.setName("dimensionsPanel"); // NOI18N

                dimensionsTitle.setText(resourceMap.getString("dimensionsTitle.text")); // NOI18N
                dimensionsTitle.setName("dimensionsTitle"); // NOI18N

                keepOriginalCheckbox.setText(resourceMap.getString("keepOriginalCheckbox.text")); // NOI18N
                keepOriginalCheckbox.setName("keepOriginalCheckbox"); // NOI18N

                dim1024Checkbox.setText(resourceMap.getString("dim1024Checkbox.text")); // NOI18N
                dim1024Checkbox.setName("dim1024Checkbox"); // NOI18N

                dim800Checkbox.setText(resourceMap.getString("dim800Checkbox.text")); // NOI18N
                dim800Checkbox.setName("dim800Checkbox"); // NOI18N

                newDimensionButton.setText(resourceMap.getString("newDimensionButton.text")); // NOI18N
                newDimensionButton.setName("newDimensionButton"); // NOI18N

                javax.swing.GroupLayout dimensionsPanelLayout = new javax.swing.GroupLayout(dimensionsPanel);
                dimensionsPanel.setLayout(dimensionsPanelLayout);
                dimensionsPanelLayout.setHorizontalGroup(
                        dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dimensionsPanelLayout.createSequentialGroup()
                                .addGroup(dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dimensionsTitle)
                                        .addComponent(keepOriginalCheckbox)
                                        .addComponent(dim1024Checkbox)
                                        .addComponent(dim800Checkbox)
                                        .addComponent(newDimensionButton))
                                .addContainerGap(78, Short.MAX_VALUE))
                );
                dimensionsPanelLayout.setVerticalGroup(
                        dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dimensionsPanelLayout.createSequentialGroup()
                                .addComponent(dimensionsTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keepOriginalCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dim1024Checkbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dim800Checkbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(newDimensionButton))
                );

                horizontalSeparator.setName("horizontalSeparator"); // NOI18N

                searchButton.setText(resourceMap.getString("searchButton.text")); // NOI18N
                searchButton.setName("searchButton"); // NOI18N

                downloadProgressButton.setText(resourceMap.getString("downloadProgressButton.text")); // NOI18N
                downloadProgressButton.setName("downloadProgressButton"); // NOI18N

                keywordsLabel.setText(resourceMap.getString("keywordsLabel.text")); // NOI18N
                keywordsLabel.setName("keywordsLabel"); // NOI18N

                keywordsTextfield.setText(resourceMap.getString("keywordsTextfield.text")); // NOI18N
                keywordsTextfield.setName("keywordsTextfield"); // NOI18N

                uploadedDateSeparator.setText(resourceMap.getString("uploadedDateSeparator.text")); // NOI18N
                uploadedDateSeparator.setName("uploadedDateSeparator"); // NOI18N

                uploadedDateTillSpinner.setModel(new javax.swing.SpinnerDateModel());
                uploadedDateTillSpinner.setName("uploadedDateTillSpinner"); // NOI18N

                uploadedDateFromSpinner.setModel(new javax.swing.SpinnerDateModel());
                uploadedDateFromSpinner.setName("uploadedDateFromSpinner"); // NOI18N

                uploadedDateLabel.setText(resourceMap.getString("uploadedDateLabel.text")); // NOI18N
                uploadedDateLabel.setName("uploadedDateLabel"); // NOI18N

                searchPhotosTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                searchPhotosTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                searchPhotosTitle.setText(resourceMap.getString("searchPhotosTitle.text")); // NOI18N
                searchPhotosTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                searchPhotosTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                searchPhotosTitle.setName("searchPhotosTitle"); // NOI18N
                searchPhotosTitle.setOpaque(true);

                searchEngineCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "via Flickr", "via Google Image Search" }));
                searchEngineCombobox.setName("searchEngineCombobox"); // NOI18N

                gpsLatTextfield.setText(resourceMap.getString("gpsLatTextfield.text")); // NOI18N
                gpsLatTextfield.setName("gpsLatTextfield"); // NOI18N

                gpsLonTextfield.setText(resourceMap.getString("gpsLonTextfield.text")); // NOI18N
                gpsLonTextfield.setName("gpsLonTextfield"); // NOI18N

                gpsLabel.setText(resourceMap.getString("gpsLabel.text")); // NOI18N
                gpsLabel.setName("gpsLabel"); // NOI18N

                gpsRadiusTextfield.setText(resourceMap.getString("gpsRadiusTextfield.text")); // NOI18N
                gpsRadiusTextfield.setName("gpsRadiusTextfield"); // NOI18N

                contextLabel.setText(resourceMap.getString("contextLabel.text")); // NOI18N
                contextLabel.setName("contextLabel"); // NOI18N

                contextCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "indoor", "outdoor" }));
                contextCombobox.setName("contextCombobox"); // NOI18N

                licenseLabel.setText(resourceMap.getString("licenseLabel.text")); // NOI18N
                licenseLabel.setName("licenseLabel"); // NOI18N

                licenseCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Creative Commons" }));
                licenseCombobox.setName("licenseCombobox"); // NOI18N

                takenDateFromSpinner.setModel(new javax.swing.SpinnerDateModel());
                takenDateFromSpinner.setName("takenDateFromSpinner"); // NOI18N

                takenDateTillSpinner.setModel(new javax.swing.SpinnerDateModel());
                takenDateTillSpinner.setName("takenDateTillSpinner"); // NOI18N

                takenDateLabel.setText(resourceMap.getString("takenDateLabel.text")); // NOI18N
                takenDateLabel.setName("takenDateLabel"); // NOI18N

                takenDateSeparator.setText(resourceMap.getString("takenDateSeparator.text")); // NOI18N
                takenDateSeparator.setName("takenDateSeparator"); // NOI18N

                downloadFolderButton.setText(resourceMap.getString("downloadFolderButton.text")); // NOI18N
                downloadFolderButton.setName("downloadFolderButton"); // NOI18N

                downloadFolderTextfield.setText(resourceMap.getString("downloadFolderTextfield.text")); // NOI18N
                downloadFolderTextfield.setName("downloadFolderTextfield"); // NOI18N

                downloadFolderLabel.setText(resourceMap.getString("downloadFolderLabel.text")); // NOI18N
                downloadFolderLabel.setName("downloadFolderLabel"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(downloadProgressButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(horizontalSeparator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(searchPhotosTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(searchEngineCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(licenseLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(licenseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                                                .addComponent(contextLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(contextCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(downloadFolderLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(downloadFolderTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(downloadFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(keywordsLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(keywordsTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(gpsLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(gpsLatTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(gpsLonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(gpsRadiusTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(takenDateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(uploadedDateLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(takenDateFromSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(uploadedDateFromSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(uploadedDateSeparator)
                                                                        .addComponent(takenDateSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(takenDateTillSpinner)
                                                                        .addComponent(uploadedDateTillSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addComponent(verticalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(downloadOptionsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(dimensionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(siftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(downloadOptionsTitle)
                                                .addGap(18, 18, 18)
                                                .addComponent(siftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(dimensionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(searchPhotosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchEngineCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(verticalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(keywordsLabel)
                                                                        .addComponent(keywordsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(gpsLabel)
                                                                        .addComponent(gpsLatTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(gpsLonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(gpsRadiusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(20, 20, 20)
                                                                                .addComponent(takenDateLabel)
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(uploadedDateLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(11, 11, 11)
                                                                                                .addComponent(takenDateSeparator))
                                                                                        .addComponent(takenDateTillSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(takenDateFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(uploadedDateFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(uploadedDateSeparator))
                                                                                        .addComponent(uploadedDateTillSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(licenseLabel)
                                                                        .addComponent(licenseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(contextCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(contextLabel))
                                                                .addGap(14, 14, 14)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(downloadFolderTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(downloadFolderLabel)
                                                                        .addComponent(downloadFolderButton))))))
                                .addGap(18, 18, 18)
                                .addComponent(horizontalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(downloadProgressButton)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox contextCombobox;
        private javax.swing.JLabel contextLabel;
        private javax.swing.JCheckBox dim1024Checkbox;
        private javax.swing.JCheckBox dim800Checkbox;
        private javax.swing.JPanel dimensionsPanel;
        private javax.swing.JLabel dimensionsTitle;
        private javax.swing.JButton downloadFolderButton;
        private javax.swing.JLabel downloadFolderLabel;
        private javax.swing.JTextField downloadFolderTextfield;
        private javax.swing.JLabel downloadOptionsTitle;
        private javax.swing.JButton downloadProgressButton;
        private javax.swing.JLabel gpsLabel;
        private javax.swing.JTextField gpsLatTextfield;
        private javax.swing.JTextField gpsLonTextfield;
        private javax.swing.JTextField gpsRadiusTextfield;
        private javax.swing.JSeparator horizontalSeparator;
        private javax.swing.JCheckBox keepOriginalCheckbox;
        private javax.swing.JLabel keywordsLabel;
        private javax.swing.JTextField keywordsTextfield;
        private javax.swing.JComboBox licenseCombobox;
        private javax.swing.JLabel licenseLabel;
        private javax.swing.JButton newDimensionButton;
        private javax.swing.JButton searchButton;
        private javax.swing.JComboBox searchEngineCombobox;
        private javax.swing.JLabel searchPhotosTitle;
        private javax.swing.JCheckBox siftCheckbox;
        private javax.swing.JTextArea siftLegend;
        private javax.swing.JPanel siftPanel;
        private javax.swing.JSpinner takenDateFromSpinner;
        private javax.swing.JLabel takenDateLabel;
        private javax.swing.JLabel takenDateSeparator;
        private javax.swing.JSpinner takenDateTillSpinner;
        private javax.swing.JSpinner uploadedDateFromSpinner;
        private javax.swing.JLabel uploadedDateLabel;
        private javax.swing.JLabel uploadedDateSeparator;
        private javax.swing.JSpinner uploadedDateTillSpinner;
        private javax.swing.JSeparator verticalSeparator;
        // End of variables declaration//GEN-END:variables

}
