
/*
 * PickPhotosDashboard.java
 *
 * Created on Mar 7, 2011, 4:05:47 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class PickPhotosDashboard extends javax.swing.JPanel {

    /** Creates new form PickPhotosDashboard */
    public PickPhotosDashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonDownloadFromInternet = new javax.swing.JButton();
                labelRecentKeywords = new javax.swing.JLabel();
                buttonChooseFromFolder = new javax.swing.JButton();
                scrollPaneRecentKeywords = new javax.swing.JScrollPane();
                listRecentKeywords = new javax.swing.JList();
                scrollPaneRecentFolders = new javax.swing.JScrollPane();
                listRecentFolders = new javax.swing.JList();
                labelRecentFolders = new javax.swing.JLabel();
                labelOr = new javax.swing.JLabel();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(PickPhotosDashboard.class);
                buttonDownloadFromInternet.setText(resourceMap.getString("buttonDownloadFromInternet.text")); // NOI18N
                buttonDownloadFromInternet.setName("buttonDownloadFromInternet"); // NOI18N

                labelRecentKeywords.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                labelRecentKeywords.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                labelRecentKeywords.setText(resourceMap.getString("labelRecentKeywords.text")); // NOI18N
                labelRecentKeywords.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                labelRecentKeywords.setName("labelRecentKeywords"); // NOI18N
                labelRecentKeywords.setOpaque(true);

                buttonChooseFromFolder.setText(resourceMap.getString("buttonChooseFromFolder.text")); // NOI18N
                buttonChooseFromFolder.setName("buttonChooseFromFolder"); // NOI18N

                scrollPaneRecentKeywords.setName("scrollPaneRecentKeywords"); // NOI18N

                listRecentKeywords.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                listRecentKeywords.setName("listRecentKeywords"); // NOI18N
                scrollPaneRecentKeywords.setViewportView(listRecentKeywords);

                scrollPaneRecentFolders.setName("scrollPaneRecentFolders"); // NOI18N

                listRecentFolders.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                listRecentFolders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                listRecentFolders.setName("listRecentFolders"); // NOI18N
                scrollPaneRecentFolders.setViewportView(listRecentFolders);

                labelRecentFolders.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                labelRecentFolders.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                labelRecentFolders.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                labelRecentFolders.setText(resourceMap.getString("labelRecentFolders.text")); // NOI18N
                labelRecentFolders.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                labelRecentFolders.setName("labelRecentFolders"); // NOI18N
                labelRecentFolders.setOpaque(true);

                labelOr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                labelOr.setText(resourceMap.getString("labelOr.text")); // NOI18N
                labelOr.setName("labelOr"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelRecentKeywords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrollPaneRecentKeywords)
                                        .addComponent(buttonDownloadFromInternet, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(labelOr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(labelRecentFolders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrollPaneRecentFolders)
                                        .addComponent(buttonChooseFromFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonDownloadFromInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonChooseFromFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(labelOr))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelRecentKeywords)
                                        .addComponent(labelRecentFolders))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(scrollPaneRecentKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollPaneRecentFolders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buttonChooseFromFolder;
        private javax.swing.JButton buttonDownloadFromInternet;
        private javax.swing.JLabel labelOr;
        private javax.swing.JLabel labelRecentFolders;
        private javax.swing.JLabel labelRecentKeywords;
        private javax.swing.JList listRecentFolders;
        private javax.swing.JList listRecentKeywords;
        private javax.swing.JScrollPane scrollPaneRecentFolders;
        private javax.swing.JScrollPane scrollPaneRecentKeywords;
        // End of variables declaration//GEN-END:variables

}
