
/*
 * SfmSetup.java
 *
 * Created on Mar 9, 2011, 1:17:54 PM
 */

package baccord.ui;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class Settings extends javax.swing.JPanel {

    /** Creates new form SfmSetup */
    public Settings() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                settingsTitle = new javax.swing.JLabel();
                bundlerBaseTextField = new javax.swing.JTextField();
                bundlerBaseButton = new javax.swing.JButton();
                bundlerBaseLabel = new javax.swing.JLabel();
                keypointTextField = new javax.swing.JTextField();
                keypointButton = new javax.swing.JButton();
                keypointLabel = new javax.swing.JLabel();
                pmvsBaseLabel = new javax.swing.JLabel();
                pmvsBaseTextField = new javax.swing.JTextField();
                pmvsBaseButton = new javax.swing.JButton();
                cmvsBaseTextField = new javax.swing.JTextField();
                cmvsBaseLabel = new javax.swing.JLabel();
                cmvsBaseButton = new javax.swing.JButton();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(Settings.class);
                settingsTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                settingsTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                settingsTitle.setText(resourceMap.getString("settingsTitle.text")); // NOI18N
                settingsTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                settingsTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                settingsTitle.setName("settingsTitle"); // NOI18N
                settingsTitle.setOpaque(true);

                bundlerBaseTextField.setText(resourceMap.getString("bundlerBaseTextField.text")); // NOI18N
                bundlerBaseTextField.setName("bundlerBaseTextField"); // NOI18N

                bundlerBaseButton.setText(resourceMap.getString("bundlerBaseButton.text")); // NOI18N
                bundlerBaseButton.setName("bundlerBaseButton"); // NOI18N

                bundlerBaseLabel.setText(resourceMap.getString("bundlerBaseLabel.text")); // NOI18N
                bundlerBaseLabel.setName("bundlerBaseLabel"); // NOI18N

                keypointTextField.setText(resourceMap.getString("keypointTextField.text")); // NOI18N
                keypointTextField.setName("keypointTextField"); // NOI18N

                keypointButton.setText(resourceMap.getString("keypointButton.text")); // NOI18N
                keypointButton.setName("keypointButton"); // NOI18N

                keypointLabel.setText(resourceMap.getString("keypointLabel.text")); // NOI18N
                keypointLabel.setName("keypointLabel"); // NOI18N

                pmvsBaseLabel.setText(resourceMap.getString("pmvsBaseLabel.text")); // NOI18N
                pmvsBaseLabel.setName("pmvsBaseLabel"); // NOI18N

                pmvsBaseTextField.setText(resourceMap.getString("pmvsBaseTextField.text")); // NOI18N
                pmvsBaseTextField.setName("pmvsBaseTextField"); // NOI18N

                pmvsBaseButton.setText(resourceMap.getString("pmvsBaseButton.text")); // NOI18N
                pmvsBaseButton.setName("pmvsBaseButton"); // NOI18N

                cmvsBaseTextField.setText(resourceMap.getString("cmvsBaseTextField.text")); // NOI18N
                cmvsBaseTextField.setName("cmvsBaseTextField"); // NOI18N

                cmvsBaseLabel.setText(resourceMap.getString("cmvsBaseLabel.text")); // NOI18N
                cmvsBaseLabel.setName("cmvsBaseLabel"); // NOI18N

                cmvsBaseButton.setText(resourceMap.getString("cmvsBaseButton.text")); // NOI18N
                cmvsBaseButton.setName("cmvsBaseButton"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bundlerBaseLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(bundlerBaseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bundlerBaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(keypointLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(keypointTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(keypointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pmvsBaseLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(pmvsBaseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pmvsBaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmvsBaseLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(cmvsBaseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmvsBaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(settingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bundlerBaseLabel, cmvsBaseLabel, keypointLabel, pmvsBaseLabel});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(settingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bundlerBaseLabel)
                                        .addComponent(bundlerBaseButton)
                                        .addComponent(bundlerBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(keypointLabel)
                                        .addComponent(keypointButton)
                                        .addComponent(keypointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pmvsBaseLabel)
                                        .addComponent(pmvsBaseButton)
                                        .addComponent(pmvsBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmvsBaseLabel)
                                        .addComponent(cmvsBaseButton)
                                        .addComponent(cmvsBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(154, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bundlerBaseButton;
        private javax.swing.JLabel bundlerBaseLabel;
        private javax.swing.JTextField bundlerBaseTextField;
        private javax.swing.JButton cmvsBaseButton;
        private javax.swing.JLabel cmvsBaseLabel;
        private javax.swing.JTextField cmvsBaseTextField;
        private javax.swing.JButton keypointButton;
        private javax.swing.JLabel keypointLabel;
        private javax.swing.JTextField keypointTextField;
        private javax.swing.JButton pmvsBaseButton;
        private javax.swing.JLabel pmvsBaseLabel;
        private javax.swing.JTextField pmvsBaseTextField;
        private javax.swing.JLabel settingsTitle;
        // End of variables declaration//GEN-END:variables

}
