
/*
 * SfmProgress.java
 *
 * Created on Mar 9, 2011, 1:17:54 PM
 */

package baccord.ui;

import baccord.BaccordApp;
import baccord.business.settings.Settings;
import baccord.business.sfm.StructureFromMotion;
import com.google.inject.Inject;
import java.io.IOException;

/**
 *
 * @author Ondřej Macoszek <ondra@macoszek.cz>
 */
public class SfmProgress extends BaseUi 
{
	@Inject private StructureFromMotion sfm;
	@Inject private Settings settings;
	
	public SfmProgress() 
	{
		initComponents();
	}

	@Override
	public void start()
	{
		super.start();
		sfm.start();
	}
	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                continueButton = new javax.swing.JButton();
                horizontalSeparator = new javax.swing.JSeparator();
                sfmTitle = new javax.swing.JLabel();
                stopButton = new javax.swing.JButton();
                browseOutputButton = new javax.swing.JButton();
                progressTextPane = new javax.swing.JTextPane();

                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(baccord.BaccordApp.class).getContext().getResourceMap(SfmProgress.class);
                continueButton.setFont(resourceMap.getFont("continueButton.font")); // NOI18N
                continueButton.setText(resourceMap.getString("continueButton.text")); // NOI18N
                continueButton.setName("continueButton"); // NOI18N
                continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                continueButtonMouseClicked(evt);
                        }
                });

                horizontalSeparator.setName("horizontalSeparator"); // NOI18N

                sfmTitle.setBackground(resourceMap.getColor("sectionTitle.background")); // NOI18N
                sfmTitle.setFont(resourceMap.getFont("sectionTitle.font")); // NOI18N
                sfmTitle.setText(resourceMap.getString("sfmTitle.text")); // NOI18N
                sfmTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                sfmTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                sfmTitle.setName("sfmTitle"); // NOI18N
                sfmTitle.setOpaque(true);

                stopButton.setText(resourceMap.getString("stopButton.text")); // NOI18N
                stopButton.setName("stopButton"); // NOI18N
                stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                stopButtonMouseClicked(evt);
                        }
                });

                browseOutputButton.setText(resourceMap.getString("browseOutputButton.text")); // NOI18N
                browseOutputButton.setName("browseOutputButton"); // NOI18N
                browseOutputButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                browseOutputButtonMouseClicked(evt);
                        }
                });

                progressTextPane.setName("progressTextPane"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(horizontalSeparator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(sfmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(stopButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(browseOutputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                                                .addComponent(continueButton))
                                        .addComponent(progressTextPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {browseOutputButton, continueButton});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sfmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stopButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(progressTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horizontalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(browseOutputButton)
                                        .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {browseOutputButton, continueButton});

        }// </editor-fold>//GEN-END:initComponents

    private void browseOutputButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_browseOutputButtonMouseClicked
    {//GEN-HEADEREND:event_browseOutputButtonMouseClicked
		try {
			Process p = new ProcessBuilder(
				settings.get(Settings.FILE_EXPLORER_PATH),
				sfm.getOutputDirectory()
			).start(); 
		} catch (IOException ex) {
			Dialog.error(this, "Cannot open file browser");
		} 
    }//GEN-LAST:event_browseOutputButtonMouseClicked

    private void continueButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_continueButtonMouseClicked
    {//GEN-HEADEREND:event_continueButtonMouseClicked
	    if(sfm.isRunning()) {
		    Dialog.error(this, "Structure from motion is still running");
		    return;
	    }
	    BaccordApp.getApplication().changeScreen(MvsProgress.class);
    }//GEN-LAST:event_continueButtonMouseClicked

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_stopButtonMouseClicked
    {//GEN-HEADEREND:event_stopButtonMouseClicked
	    sfm.stop();
	    BaccordApp.getApplication().changeScreen(SfmSetup.class);
    }//GEN-LAST:event_stopButtonMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton browseOutputButton;
        private javax.swing.JButton continueButton;
        private javax.swing.JSeparator horizontalSeparator;
        private javax.swing.JTextPane progressTextPane;
        private javax.swing.JLabel sfmTitle;
        private javax.swing.JButton stopButton;
        // End of variables declaration//GEN-END:variables

}
